// these data is generated by AI

export const lifeConcepts = [
  {
    category: "Colors",
    items: [
      "Red", "Blue", "Green", "Yellow",
      "Purple", "Orange", "Pink", "Black",
      "White", "Gray", "Brown", "Cyan",
      "Magenta", "Teal", "Gold", "Silver"
    ]
  },
  {
    category: "Sports",
    items: [
      "Football", "Basketball", "Tennis", "Baseball",
      "Swimming", "Cycling", "Boxing", "Golf",
      "Rugby", "Volleyball", "Hockey", "Cricket",
      "Surfing", "Skiing", "Running", "Wrestling"
    ]
  },
  {
    category: "Films",
    items: [
      "Inception", "Titanic", "Avatar", "Gladiator",
      "Interstellar", "Joker", "The Matrix", "Frozen",
      "Coco", "The Godfather", "Shrek", "Rocky",
      "Dune", "Up", "Memento", "Parasite"
    ]
  },
  {
    category: "Emotions",
    items: [
      "Joy", "Sadness", "Anger", "Fear",
      "Love", "Hope", "Excitement", "Anxiety",
      "Pride", "Jealousy", "Relief", "Gratitude",
      "Loneliness", "Curiosity", "Peace", "Surprise"
    ]
  },
  {
    category: "Foods",
    items: [
      "Pizza", "Burger", "Pasta", "Sushi",
      "Tacos", "Salad", "Steak", "Soup",
      "Curry", "Rice", "Bread", "Ice Cream",
      "Chocolate", "Pancakes", "Fries", "Dumplings"
    ]
  },
  {
    category: "Animals",
    items: [
      "Lion", "Tiger", "Elephant", "Dolphin",
      "Eagle", "Shark", "Panda", "Wolf",
      "Fox", "Bear", "Horse", "Rabbit",
      "Kangaroo", "Penguin", "Owl", "Cheetah"
    ]
  },
  {
    category: "Music Genres",
    items: [
      "Rock", "Pop", "Jazz", "Hip Hop",
      "Classical", "Blues", "Country", "Reggae",
      "Metal", "EDM", "Soul", "Funk",
      "Disco", "Techno", "Opera", "Folk"
    ]
  },
  {
    category: "Weather",
    items: [
      "Sunny", "Rainy", "Cloudy", "Stormy",
      "Windy", "Snowy", "Foggy", "Humid",
      "Dry", "Cold", "Hot", "Mild",
      "Hail", "Thunder", "Lightning", "Breezy"
    ]
  },
  {
    category: "Careers",
    items: [
      "Doctor", "Engineer", "Teacher", "Designer",
      "Chef", "Pilot", "Writer", "Artist",
      "Scientist", "Lawyer", "Nurse", "Photographer",
      "Musician", "Architect", "Developer", "Farmer"
    ]
  },
  {
    category: "Hobbies",
    items: [
      "Reading", "Painting", "Gardening", "Cooking",
      "Photography", "Gaming", "Fishing", "Hiking",
      "Dancing", "Writing", "Knitting", "Yoga",
      "Traveling", "Drawing", "Coding", "Cycling"
    ]
  },
  {
    category: "Countries",
    items: [
      "Germany", "Japan", "Brazil", "Canada",
      "France", "India", "Australia", "Italy",
      "Mexico", "Norway", "Egypt", "Argentina",
      "Spain", "China", "Kenya", "Sweden"
    ]
  },
  {
    category: "Planets & Space",
    items: [
      "Mercury", "Venus", "Earth", "Mars",
      "Jupiter", "Saturn", "Uranus", "Neptune",
      "Galaxy", "Comet", "Asteroid", "Black Hole",
      "Moon", "Sun", "Nebula", "Rocket"
    ]
  },
  {
    category: "Technology",
    items: [
      "AI", "Blockchain", "Cloud", "Cybersecurity",
      "VR", "AR", "Robotics", "IoT",
      "Quantum Computing", "5G", "Big Data", "Automation",
      "Drones", "Smartphones", "Wearables", "Servers"
    ]
  },
  {
    category: "Nature",
    items: [
      "Mountain", "River", "Forest", "Ocean",
      "Desert", "Waterfall", "Volcano", "Canyon",
      "Island", "Glacier", "Lake", "Rainforest",
      "Beach", "Valley", "Cave", "Cliff"
    ]
  },
  {
    category: "Personality Traits",
    items: [
      "Kind", "Brave", "Creative", "Honest",
      "Funny", "Patient", "Confident", "Curious",
      "Loyal", "Optimistic", "Calm", "Wise",
      "Generous", "Focused", "Adventurous", "Independent"
    ]
  },
  {
    category: "School Subjects",
    items: [
      "Math", "Science", "History", "Geography",
      "Physics", "Chemistry", "Biology", "Art",
      "Music", "Literature", "Economics", "Philosophy",
      "Programming", "Psychology", "Sociology", "Astronomy"
    ]
  },
  {
    category: "Vehicles",
    items: [
      "Car", "Bike", "Truck", "Bus",
      "Train", "Plane", "Boat", "Helicopter",
      "Scooter", "Submarine", "Yacht", "Tractor",
      "Motorcycle", "Van", "Skateboard", "Jet"
    ]
  },
  {
    category: "Games",
    items: [
      "Chess", "Poker", "Minecraft", "Fortnite",
      "Monopoly", "Sudoku", "Scrabble", "Tetris",
      "Uno", "FIFA", "Call of Duty", "Mario Kart",
      "Zelda", "Among Us", "Valorant", "Roblox"
    ]
  },
  {
    category: "Life Goals",
    items: [
      "Happiness", "Success", "Health", "Freedom",
      "Love", "Wisdom", "Adventure", "Peace",
      "Wealth", "Creativity", "Knowledge", "Family",
      "Travel", "Growth", "Purpose", "Balance"
    ]
  },
  {
    category: "Cities",
    items: [
      "Berlin", "Tokyo", "Paris", "New York",
      "London", "Dubai", "Sydney", "Rome",
      "Toronto", "Bangkok", "Istanbul", "Seoul",
      "Barcelona", "Singapore", "Cape Town", "Los Angeles"
    ]
  }
];